version: "2"
services:
    proxy:
      build: ./proxy
      ports:
          - "12345:12345"
      depends_on:
       - redis
       - flask1
       - flask2
       - flask3

    flask1:
      build: ./app1
      ports:
          - "6701:6701"
      depends_on:
       - mysql
       - redis

    flask2:
      build: ./app2
      ports:
          - "6702:6702"
      depends_on:
       - mysql
       - redis

    flask3:
      build: ./app3
      ports:
          - "6703:6703"
      depends_on:
       - mysql
       - redis

    mysql:
        hostname: mysql
        ports:
         - "3306:3306"
        image: mysql
        environment:
         MYSQL_ROOT_PASSWORD: test
         MYSQL_DATABASE: expsys
         MYSQL_USER: root

    redis:
        image: redis
        ports:
            - "6379:6379"
